Add files via upload
Hi Lucas, 
I ran your example called thermallag_correction.py, and when I tried to use the apply_mask function (from the ThermalLag class), I got the following error:
TypeError: ufunc 'bitwise_or' output (typecode 'O') could not be coerced to provided output parameter (typecode '?') according to the casting rule ''same_kind'', on line 94.

I did some changes to your function, included the "np.bitwise_or" and "np.bitwise_and" functions and transformed the mask variable into a boolean (that's how I could manage to use the function lambda and the mask variable to work).
Let me know if this make sense.

Thanks!
Mariana